# Alissa settings
alissa_base_uri = ''
alissa_client_id = ''
alissa_client_secret = ''
alissa_username = ''
alissa_password = ''
mongodb_localhost = 'mongodb://localhost:27017/'
logging_file = './logging_config.yml'
vusualizer_path = './'
